---
journal_path: ~/Documents/journal.org

twitter:
  access_token_secret_cmd: pass twitter/reckerbot/access-token-secret
  access_token_cmd: pass twitter/reckerbot/access-token
  consumer_api_key_cmd: pass twitter/reckerbot/consumer-api-key
  consumer_api_secret_cmd: pass twitter/reckerbot/consumer-api-secret-key

slacks:
  -
    channel: '#blog'
    username: 'reckerbot'
    webhook_cmd: pass slack/reckerfamily/webhook | tail -1
  -
    channel: '#blog'
    username: 'reckerbot'
    webhook_cmd: pass slack/redalenfamily/webhook | tail -1
